# Generated by Django 5.0.6 on 2024-08-15 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('thumbnail_url', models.URLField()),
                ('request_count', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
